name: wealth
description: A new Flutter application.

version: 1.1.3+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Font
  google_fonts: ^0.3.10
  # DateFormat
  intl: ^0.16.1
  # Share
  share: any
  # Fonts
  flutter_icons: ^1.0.0+1
  # Pie Chart
  pie_chart: ^3.1.1
  # Chart
  fl_chart: ^0.8.7
  # Url Launcher
  url_launcher: ^5.4.2
  # Open Whatsapp
  flutter_open_whatsapp: ^0.1.2
  # DateTime Picker
  flutter_datetime_picker: ^1.3.8
  # Firebase
  firebase_auth: ^0.15.4
  cloud_firestore: 0.13.1
  firebase_storage: ^3.1.3
  firebase_crashlytics: ^0.1.3+3
  firebase_in_app_messaging: ^0.1.1+3
  firebase_messaging: any
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  flutter_facebook_login:
  google_sign_in:
  # firebase_dynamic_links: ^0.5.0+11
  # Progress indicator
  flutter_spinkit: "^4.1.2"
  # Shared Preferences
  shared_preferences: ^0.5.6+1
  # Permission Handler
  permission_handler: ^3.1.0
  # Image Picker
  image_picker: any
  cupertino_icons: ^0.1.3
  fancy_bottom_navigation: ^0.3.2
  # Unique ID
  uuid: 2.0.4
  # Connection State
  connectivity: ^0.4.3+1
  # State Management
  provider: ^2.0.1
  # SMS
  sms: any
  # Package Info
  package_info: ^0.4.0+16

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Launcher Icons
  flutter_launcher_icons: ^0.7.5

flutter:
  uses-material-design: true

  assets:
   - assets/logos/
   - assets/images/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/foreground.png"
  image_path_android: "assets/launcher/foreground.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
